### ISSUE TITLE
Fails to build with ffmpeg 8.0

### ISSUE THREAD

**Issue by lazka** [mltframework/mlt#1149]
**Describe the bug**

Builds fine with 7.1, but fails with 8.0

**To Reproduce**

I collected all the errors I get could get by letting ninja ignore errors, not sure if these are all:

```c
mlt-7.32.0/src/modules/avformat/common.c:372:12: error: 'AVFrame' has no member named 'interlaced_frame'
  372 |     avframe->interlaced_frame = !mlt_properties_get_int(frame_properties, "progressive");
      |            ^~
mlt-7.32.0/src/modules/avformat/common.c:373:12: error: 'AVFrame' has no member named 'top_field_first'
  373 |     avframe->top_field_first = mlt_properties_get_int(frame_properties, "top_field_first");
      |            ^~

mlt-7.32.0/src/modules/avformat/producer_avformat.c:2527:50: error: 'AVFrame' has no member named 'key_frame'
 2527 |                             && (self->video_frame->key_frame
      |                                                  ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2561:59: error: 'AVFrame' has no member named 'interlaced_frame'
 2561 |                     self->progressive = !self->video_frame->interlaced_frame
      |                                                           ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2567:34: error: 'AVFrame' has no member named 'interlaced_frame'
 2567 |                 self->video_frame->interlaced_frame = !self->progressive;
      |                                  ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2572:62: error: 'AVFrame' has no member named 'top_field_first'
 2572 |                     self->top_field_first = self->video_frame->top_field_first
      |                                                              ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2576:34: error: 'AVFrame' has no member named 'top_field_first'
 2576 |                 self->video_frame->top_field_first = self->top_field_first;
      |                                  ^~

mlt-7.32.0/src/modules/avformat/producer_avformat.c: In function 'get_audio_streams_info':
mlt-7.32.0/src/modules/avformat/producer_avformat.c:1583:17: error: implicit declaration of function 'avcodec_close'; did you mean 'avio_close'? [-Wimplicit-function-declaration]
 1583 |                 avcodec_close(codec_context);
      |                 ^~~~~~~~~~~~~
      |                 avio_close
mlt-7.32.0/src/modules/avformat/producer_avformat.c: In function 'sliced_h_pix_fmt_conv_proc':
mlt-7.32.0/src/modules/avformat/producer_avformat.c:1719:28: error: 'AVFrame' has no member named 'interlaced_frame'
 1719 |     interlaced = ctx->frame->interlaced_frame;
      |                            ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c: In function 'convert_image_rgb':
mlt-7.32.0/src/modules/avformat/producer_avformat.c:1868:51: error: 'AVFrame' has no member named 'interlaced_frame'
 1868 |     if (src_pix_fmt == AV_PIX_FMT_YUV420P && frame->interlaced_frame) {
      |                                                   ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c: In function 'convert_image':
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2044:57: error: 'AVFrame' has no member named 'interlaced_frame'
 2044 |             ctx.slice_w = (width < 1000) ? (256 >> frame->interlaced_frame)
      |                                                         ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2045:57: error: 'AVFrame' has no member named 'interlaced_frame'
 2045 |                                          : (512 >> frame->interlaced_frame);
      |                                                         ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2055:23: error: 'AVFrame' has no member named 'interlaced_frame'
 2055 |             c *= frame->interlaced_frame ? 2 : 1;
      |                       ^~
mlt-7.32.0/src/modules/avformat/producer_avformat.c:2058:22: error: 'AVFrame' has no member named 'interlaced_frame'
 2058 |             c = frame->interlaced_frame ? 2 : 1;

mlt-7.32.0/src/modules/avformat/producer_avformat.c: In function 'guess_frame_rate':
mlt-7.32.0/src/modules/avformat/producer_avformat.c:425:78: error: 'AVCodecContext' has no member named 'ticks_per_frame'
  425 |         frame_rate.den = self->video_codec->time_base.num * self->video_codec->ticks_per_frame;
      |                                                                              ^~

mlt-7.32.0/src/modules/avformat/producer_avformat.c: In function 'get_projection':
mlt-7.32.0/src/modules/avformat/producer_avformat.c:339:40: error: implicit declaration of function 'av_stream_get_side_data'; did you mean 'av_frame_get_side_data'? [-Wimplicit-function-declaration]
  339 |         = (const AVSphericalMapping *) av_stream_get_side_data(st, AV_PKT_DATA_SPHERICAL, NULL);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~
      |                                        av_frame_get_side_data

mlt-7.32.0/src/modules/avformat/consumer_avformat.c:1926:16: error: 'AVFrame' has no member named 'interlaced_frame'
 1926 |         avframe->interlaced_frame = !mlt_properties_get_int(frame_properties, "progressive");
      |                ^~
mlt-7.32.0/src/modules/avformat/consumer_avformat.c:1927:16: error: 'AVFrame' has no member named 'top_field_first'
 1927 |         avframe->top_field_first = mlt_properties_get_int(frame_properties, "top_field_first");
      |                ^~

mlt-7.32.0/src/modules/avformat/link_avfilter.c: In function 'link_get_image':
mlt-7.32.0/src/modules/avformat/link_avfilter.c:920:25: error: 'AVFrame' has no member named 'interlaced_frame'
  920 |         pdata->avinframe->interlaced_frame = !mlt_properties_get_int(frame_properties,
      |                         ^~
mlt-7.32.0/src/modules/avformat/link_avfilter.c:922:25: error: 'AVFrame' has no member named 'top_field_first'
  922 |         pdata->avinframe->top_field_first = mlt_properties_get_int(frame_properties,
      |                         ^~

mlt-7.32.0/src/modules/avformat/filter_swscale.c: In function 'filter_scale':
mlt-7.32.0/src/modules/avformat/filter_swscale.c:173:18: error: 'AVFrame' has no member named 'interlaced_frame'
  173 |         avinframe->interlaced_frame = !mlt_properties_get_int(properties, "progressive");
      |                  ^~
mlt-7.32.0/src/modules/avformat/filter_swscale.c:174:18: error: 'AVFrame' has no member named 'top_field_first'
  174 |         avinframe->top_field_first = mlt_properties_get_int(properties, "top_field_first");
      |                  ^~

mlt-7.32.0/src/modules/avformat/filter_avfilter.c: In function 'filter_get_image':
mlt-7.32.0/src/modules/avformat/filter_avfilter.c:805:25: error: 'AVFrame' has no member named 'interlaced_frame'
  805 |         pdata->avinframe->interlaced_frame = !mlt_properties_get_int(frame_properties,
      |                         ^~
mlt-7.32.0/src/modules/avformat/filter_avfilter.c:807:25: error: 'AVFrame' has no member named 'top_field_first'
  807 |         pdata->avinframe->top_field_first = mlt_properties_get_int(frame_properties,
      |                         ^~

mlt-7.32.0/src/modules/avformat/common.c: In function 'mlt_image_to_avframe':
mlt-7.32.0/src/modules/avformat/common.c:372:12: error: 'AVFrame' has no member named 'interlaced_frame'
  372 |     avframe->interlaced_frame = !mlt_properties_get_int(frame_properties, "progressive");
      |            ^~
mlt-7.32.0/src/modules/avformat/common.c:373:12: error: 'AVFrame' has no member named 'top_field_first'
  373 |     avframe->top_field_first = mlt_properties_get_int(frame_properties, "top_field_first");
      |            ^~
```

**Expected behavior**

It working.

**Desktop (please complete the following information):**

This is on Windows with gcc
 - OS: Windows + gcc
- MLT/melt version: 7.32.0

**Comment by ddennedy** [comment]
Already fixed in ae83cee

**Comment by lazka** [comment]
Oops, I should have looked. Thanks!
