### ISSUE TITLE
OpenCV compile error

### ISSUE THREAD

**Issue by faridosc** [mltframework/mlt#636]
Trying to build using OpenCV 4.5.1I am getting an error:
```
filter_opencv_tracker.cpp: In function ‘void analyze(mlt_filter, cv::Mat, private_data*, int, int, int, int)’:
filter_opencv_tracker.cpp:148:24: error: ‘cv::TrackerMOSSE’ has not been declared
  148 |    data->tracker = cv::TrackerMOSSE::create();
      |                        ^~~~~~~~~~~~
filter_opencv_tracker.cpp:157:24: error: ‘cv::TrackerTLD’ has not been declared
  157 |    data->tracker = cv::TrackerTLD::create();
      |                        ^~~~~~~~~~
filter_opencv_tracker.cpp:161:24: error: ‘cv::TrackerBoosting’ has not been declared
  161 |    data->tracker = cv::TrackerBoosting::create();
      |                        ^~~~~~~~~~~~~~~
filter_opencv_tracker.cpp:227:28: error: could not convert ‘data->private_data::tracker.cv::Ptr<cv::Tracker>::operator->()->cv::Tracker::init(cv::_InputArray(cvFrame), cv::Rect_<_Tp>::operator cv::Rect_<_Tp2>() const [with _Tp2 = int; _Tp = double]())’ from ‘void’ to ‘bool’
  227 |    if ( data->tracker->init( cvFrame, data->boundingBox ) ) {
      |         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            void
filter_opencv_tracker.cpp:242:41: error: cannot bind non-const lvalue reference of type ‘cv::Rect&’ {aka ‘cv::Rect_<int>&’} to an rvalue of type ‘cv::Rect_<int>’
  242 |   data->tracker->update( cvFrame, data->boundingBox );
      |                                   ~~~~~~^~~~~~~~~~~
In file included from /usr/include/opencv4/opencv2/core.hpp:58,
                 from /usr/include/opencv4/opencv2/tracking.hpp:8,
                 from filter_opencv_tracker.cpp:21:
/usr/include/opencv4/opencv2/core/types.hpp:1905:1: note:   after user-defined conversion: ‘cv::Rect_<_Tp>::operator cv::Rect_<_Tp2>() const [with _Tp2 = int; _Tp = double]’
 1905 | Rect_<_Tp>::operator Rect_<_Tp2>() const
      | ^~~~~~~~~~
In file included from /usr/include/opencv4/opencv2/tracking.hpp:9,
                 from filter_opencv_tracker.cpp:21:
/usr/include/opencv4/opencv2/video/tracking.hpp:737:48: note:   initializing argument 2 of ‘virtual bool cv::Tracker::update(cv::InputArray, cv::Rect&)’
  737 |     bool update(InputArray image, CV_OUT Rect& boundingBox) = 0;
      |                                          ~~~~~~^~~~~~~~~~~
make[2]: *** [<builtin>: filter_opencv_tracker.o] Error 1

```

**Comment by PhobosK** [comment]
Same situation here on a Gentoo 64 nit system

**Comment by iadegesso** [comment]
Same here in Gentoo amd64 with 5.9.14 kernel and OpenCV 4.5.1.

Iade Gesso, PhD

**Comment by j-b-m** [comment]
With OpenCV 4.5.1, the tracking API was moved from the separate contrib repository to the main OpenCV repository. This will require some changes, I will try to fix this in the next days

**Comment by j-b-m** [comment]
Unfortunately, the API change in OpenCV 4.5.1 currently breaks most of the trackers. A fix is planned for 4.5.2 but no solution is currently available, so we need a fix first before this can be properly solved in MLT.
The OpenCV Tracking API issue is here: https://github.com/opencv/opencv/issues/19260

**Comment by sandsmark** [comment]
I wonder if it would be better to just disable the opencv module if there isn't a known version (i. e. a max version), opencv is the worst library I know by a long shot wrt. breaking between releases...

and I'm tempted to port the tracking away from opencv to e. g. dlib (which is one of the best libraries I know).

**Comment by sandsmark** [comment]
this fixes the build at least, no idea if it still works:

```
diff --git a/src/modules/opencv/filter_opencv_tracker.cpp b/src/modules/opencv/filter_opencv_tracker.cpp
  index b28cdb5c..517393d0 100644
  --- a/src/modules/opencv/filter_opencv_tracker.cpp
  +++ b/src/modules/opencv/filter_opencv_tracker.cpp
  @@ -25,7 +25,11 @@
   typedef struct
   {
          cv::Ptr<cv::Tracker> tracker;
  +#if CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
          cv::Rect2d boundingBox;
  +#else
  +       cv::Rect boundingBox;
  +#endif
          char * algo;
          mlt_rect startRect;
          bool initialized;
  @@ -138,7 +142,7 @@ static void analyze( mlt_filter filter, cv::Mat cvFrame, private_data* data, int
                  {
                          data->tracker = cv::TrackerKCF::create();
                  }
  -#if CV_VERSION_MAJOR > 3 || (CV_VERSION_MAJOR == 3 && CV_VERSION_MINOR >= 4 && CV_VERSION_REVISION >= 2)
  +#if (CV_VERSION_MAJOR > 3 && CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5) || (CV_VERSION_MAJOR == 3 && CV_VERSION_MINOR >= 4 && CV_VERSION_R  EVISION >= 2)
                  else if ( !strcmp(data->algo, "CSRT" ) )
                  {
                          data->tracker = cv::TrackerCSRT::create();
  @@ -152,6 +156,7 @@ static void analyze( mlt_filter filter, cv::Mat cvFrame, private_data* data, int
                  {
                          data->tracker = cv::TrackerMIL::create();
                  }
  +#if CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
                  else if ( !strcmp(data->algo, "TLD" ) )
                  {
                          data->tracker = cv::TrackerTLD::create();
  @@ -160,6 +165,7 @@ static void analyze( mlt_filter filter, cv::Mat cvFrame, private_data* data, int
                  {
                          data->tracker = cv::TrackerBoosting::create();
                  }
  +#endif // CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
   #else
                  if ( data->algo == NULL || !strcmp(data->algo, "" ) )
                  {
  @@ -224,7 +230,12 @@ static void analyze( mlt_filter filter, cv::Mat cvFrame, private_data* data, int
                          if ( data->boundingBox.height <1 ) {
                                  data->boundingBox.height = 50;
                          }
  +#if CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
                          if ( data->tracker->init( cvFrame, data->boundingBox ) ) {
  +#else
  +                       {
  +                               data->tracker->init( cvFrame, data->boundingBox );
  +#endif
                                  data->initialized = true;
                                  data->analyze = true;
                                  data->last_position = position - 1;
```

**Comment by vpinon** [comment]
Not checked, but I would rewrite the conditions (some seem always false, some would get wrong for 5.0 to 5.5 ...)

#define CV_VERSION_INT (CV_VERSION_MAJOR << 16 | CV_VERSION_MINOR << 8 | CV_VERSION_REVISION)
>   +#if CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
#if CV_VERSION_INT < 0x040500

>   +#if (CV_VERSION_MAJOR > 3 && CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5) || (CV_VERSION_MAJOR == 3 && CV_VERSION_MINOR >= 4 && CV_VERSION_REVISION >= 2)
#if CV_VERSION_INT >= 0x030402 && CV_VERSION_INT < 0x040500

>   +#if CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
#if CV_VERSION_INT < 0x040500

>   +#if CV_VERSION_MAJOR < 4 && CV_VERSION_MINOR < 5
#if CV_VERSION_INT < 0x040500

**Comment by sandsmark** [comment]
yeah, the conditionals were really annoying, might be better to move stuff to cmake and just have single #ifdefs per compatibility-version-level

**Comment by ferdnyc** [comment]
@sandsmark 

> opencv is the worst library I know by a long shot wrt. breaking between releases...

What, no love for pre-3.4 FFmpeg, AKA `av_movingtarget::API`? How quickly we forget... :wink: 

> yeah, the conditionals were really annoying, might be better to move stuff to cmake and just have single #ifdefs per compatibility-version-level

That's what I ended up doing for the Tracking stuff (not that it works yet, because the `cv::legacy::Tracker`-defining headers released with OpenCV 4.5.1 are broken):

```cmake
find_package(OpenCV 4)
if(OpenCV_VERSION VERSION_GREATER 4.5.0)
  target_compile_definitions(library PUBLIC USE_LEGACY_TRACKING=1)
endif()
```

And then I can just use `#ifdef USE_LEGACY_TRACKING` to conditionalize my code.

**Comment by sandsmark** [comment]
> What, no love for pre-3.4 FFmpeg, AKA `av_movingtarget::API`? How quickly we forget... 

Well, they sharpened their underwear (to use a hard to translate norwegian expression), most ffmpeg issues these days seem to at least be unintentional. :-P

> That's what I ended up doing for the Tracking stuff (not that it works yet, because the cv::legacy::Tracker-defining headers released with OpenCV 4.5.1 are broken) [...]

Oh yes, I noticed. Using opencv for anything feels sisyphean, have you compared the quality of the opencv tracking vs. other alternatives?

**Comment by sandsmark** [comment]
https://github.com/mltframework/mlt/pull/692 finally got around to it
