### PR TITLE
module: opencv: Remove deleted cv::Tracker::create()

### PR DESCRIPTION
**Pull request by BoboopTeam**
This static method is no longer present in OpenCV API, this workaround should fix compilation against OpenCV 3.3.0 and newer
Doxygen documentations :
v3.2: http://docs.opencv.org/3.2.0/d0/d0a/classcv_1_1Tracker.html
The old Tracker::create(char*) function seems to only support
- "MIL" – TrackerMIL
- "BOOSTING" – TrackerBoosting
So we manually check these.

v3.3: http://docs.opencv.org/3.3.0/d0/d0a/classcv_1_1Tracker.html

### CODE REVIEW

**Comment by ddennedy** [comment]
Does it work on OpenCV 3.1?

**Comment by BoboopTeam** [comment]
I cannot test it now but TrackerMIL, TrackerBoosting,  tracker TrackerMIL and TrackerKCF already existed in OpenCV 3.1.
doxygen: http://docs.opencv.org/3.1.0/d9/df8/group__tracking.html

**Comment by ddennedy** [comment]
The filter_opencv_tracker.yml mentions a TLD tracker. We should support that as well.

**Comment by BoboopTeam** [comment]
Related to issue "mlt compile fails unless opencv is disabled" #235 
@kiroma suggests to build it against openCV 3.1 as a  workaround but on some systems it may be not possible

**Comment by BoboopTeam** [comment]
@ddennedy 'TLD' tracker mode detection added

**Comment by ddennedy** [comment]
When compiling against OpenCV v3.1 on Ubuntu:artsy I get the following compile errors. I do not know opencv that well. I see there are static `createTracker()` methods for each type of tracker in 3.1 - 3.3. Is it OK to call those directly? If not, you can
```
#include <opencv2/core/version.hpp>
...
#if CV_VERSION_MAJOR == 3 && CV_VERSION_MINOR >= 3
...
```

```
make[2]: Entering directory '/root/shotcut/src/mlt/src/modules/opencv'
cc -I../.. -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -pthread -I/usr/include/opencv -I/usr/include/opencv -I/usr/include/opencv -I/usr/include/opencv   -c -o factory.o factory.c
g++ -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wno-deprecated -I../.. -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -pthread -I/usr/include/opencv -I/usr/include/opencv -I/usr/include/opencv -I/usr/include/opencv   -c -o filter_opencv_tracker.o filter_opencv_tracker.cpp
filter_opencv_tracker.cpp: In function 'void analyze(mlt_filter, cv::Mat, private_data*, int, int, int, int)':
filter_opencv_tracker.cpp:114:43: error: no matching function for call to 'cv::TrackerKCF::create()'
    data->tracker = cv::TrackerKCF::create();
                                           ^
In file included from /usr/include/opencv2/tracking.hpp:309:0,
                 from filter_opencv_tracker.cpp:21:
/usr/include/opencv2/tracking/tracker.hpp:563:31: note: candidate: static cv::Ptr<cv::Tracker> cv::Tracker::create(const cv::String&)
   CV_WRAP static Ptr<Tracker> create( const String& trackerType );
                               ^~~~~~
/usr/include/opencv2/tracking/tracker.hpp:563:31: note:   candidate expects 1 argument, 0 provided
filter_opencv_tracker.cpp:118:43: error: no matching function for call to 'cv::TrackerMIL::create()'
    data->tracker = cv::TrackerMIL::create();
                                           ^
In file included from /usr/include/opencv2/tracking.hpp:309:0,
                 from filter_opencv_tracker.cpp:21:
/usr/include/opencv2/tracking/tracker.hpp:563:31: note: candidate: static cv::Ptr<cv::Tracker> cv::Tracker::create(const cv::String&)
   CV_WRAP static Ptr<Tracker> create( const String& trackerType );
                               ^~~~~~
/usr/include/opencv2/tracking/tracker.hpp:563:31: note:   candidate expects 1 argument, 0 provided
filter_opencv_tracker.cpp:122:43: error: no matching function for call to 'cv::TrackerTLD::create()'
    data->tracker = cv::TrackerTLD::create();
                                           ^
In file included from /usr/include/opencv2/tracking.hpp:309:0,
                 from filter_opencv_tracker.cpp:21:
/usr/include/opencv2/tracking/tracker.hpp:563:31: note: candidate: static cv::Ptr<cv::Tracker> cv::Tracker::create(const cv::String&)
   CV_WRAP static Ptr<Tracker> create( const String& trackerType );
                               ^~~~~~
/usr/include/opencv2/tracking/tracker.hpp:563:31: note:   candidate expects 1 argument, 0 provided
filter_opencv_tracker.cpp:126:48: error: no matching function for call to 'cv::TrackerBoosting::create()'
    data->tracker = cv::TrackerBoosting::create();
                                                ^
In file included from /usr/include/opencv2/tracking.hpp:309:0,
                 from filter_opencv_tracker.cpp:21:
/usr/include/opencv2/tracking/tracker.hpp:563:31: note: candidate: static cv::Ptr<cv::Tracker> cv::Tracker::create(const cv::String&)
   CV_WRAP static Ptr<Tracker> create( const String& trackerType );
                               ^~~~~~
/usr/include/opencv2/tracking/tracker.hpp:563:31: note:   candidate expects 1 argument, 0 provided
<builtin>: recipe for target 'filter_opencv_tracker.o' failed
make[2]: *** [filter_opencv_tracker.o] Error 1
make[2]: Leaving directory '/root/shotcut/src/mlt/src/modules/opencv'
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/root/shotcut/src/mlt/src/modules'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by ddennedy** [comment]
This diff fixes build on < 3.3. Please test it on 3.3 and commit it if it works.
```
diff --git a/src/modules/opencv/filter_opencv_tracker.cpp b/src/modules/opencv/filter_opencv_tracker.cpp
index 91cb8d79..5df1cce2 100644
--- a/src/modules/opencv/filter_opencv_tracker.cpp
+++ b/src/modules/opencv/filter_opencv_tracker.cpp
@@ -18,6 +18,7 @@
  */
 
 #include <framework/mlt.h>
+#include <opencv2/core/version.hpp>
 #include <opencv2/tracking.hpp>
 
 
@@ -109,6 +110,7 @@ static void analyze( mlt_filter filter, cv::Mat cvFrame, private_data* data, int
         {
                // Build tracker
                data->algo = mlt_properties_get( filter_properties, "algo" );
+#if CV_VERSION_MAJOR == 3 && CV_VERSION_MINOR >= 3
                if ( !data->algo || *data->algo == '\0' || !strcmp(data->algo, "KCF" ) )
                {
                        data->tracker = cv::TrackerKCF::create();
@@ -125,6 +127,16 @@ static void analyze( mlt_filter filter, cv::Mat cvFrame, private_data* data, int
                {
                        data->tracker = cv::TrackerBoosting::create();
                }
+#else
+               if ( data->algo == NULL || !strcmp(data->algo, "" ) )
+                {
+                       data->tracker = cv::Tracker::create( "KCF" );
+               }
+               else
+               {
+                       data->tracker = cv::Tracker::create( data->algo );
+               }
+#endif
 
                // Discard previous results
                mlt_properties_set( filter_properties, "_results", "" );
```

**Comment by kiroma** [comment]
It does work with OpenCV 3.3.

**Comment by ddennedy** [comment]
This was merged with commit 9076b7 that includes my patch.

**Comment by BoboopTeam** [comment]
Thanks!
