### ISSUE TITLE
make fails due to "[...]/src/modules/avformat/filter_avcolour_space.c:186: undefined reference to `av_image_get_buffer_size'"

### ISSUE THREAD

**Issue by krichter722** [mltframework/mlt#308]
The build on Ubuntu 14.02, CentOS 6 and Debian oldstable fails due to

```
cc -shared -o ../libmltavformat.so factory.o filter_avcolour_space.o filter_avdeinterlace.o filter_swscale.o producer_avformat.o consumer_avformat.o -L../../framework -lmlt -lpthread -lm -Wl,--no-undefined -Wl,--as-needed -lavcodec  -lavutil  -lavformat  -lswscale  -lavdevice  
filter_avcolour_space.o: In function `convert_image':
/builds/krichter/mlt/src/modules/avformat/filter_avcolour_space.c:186: undefined reference to `av_image_get_buffer_size'
filter_avcolour_space.o: In function `av_convert_image':
/builds/krichter/mlt/src/modules/avformat/filter_avcolour_space.c:142: undefined reference to `av_image_fill_arrays'
/builds/krichter/mlt/src/modules/avformat/filter_avcolour_space.c:146: undefined reference to `av_image_fill_arrays'
filter_avcolour_space.o: In function `convert_image':
/builds/krichter/mlt/src/modules/avformat/filter_avcolour_space.c:186: undefined reference to `av_image_get_buffer_size'
filter_avdeinterlace.o: In function `filter_get_image':
/builds/krichter/mlt/src/modules/avformat/filter_avdeinterlace.c:318: undefined reference to `av_image_fill_arrays'
filter_swscale.o: In function `filter_scale':
/builds/krichter/mlt/src/modules/avformat/filter_swscale.c:124: undefined reference to `av_image_fill_arrays'
/builds/krichter/mlt/src/modules/avformat/filter_swscale.c:125: undefined reference to `av_image_fill_arrays'
/builds/krichter/mlt/src/modules/avformat/filter_swscale.c:153: undefined reference to `av_image_fill_arrays'
/builds/krichter/mlt/src/modules/avformat/filter_swscale.c:154: undefined reference to `av_image_fill_arrays'
producer_avformat.o:/builds/krichter/mlt/src/modules/avformat/producer_avformat.c:1456: more undefined references to `av_image_fill_arrays' follow
collect2: error: ld returned 1 exit status
Makefile:49: recipe for target '../libmltavformat.so' failed
make[2]: *** [../libmltavformat.so] Error 1
make[2]: Leaving directory '/builds/krichter/mlt/src/modules/avformat'
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/builds/krichter/mlt/src/modules'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1
```

(https://gitlab.com/krichter/mlt/pipelines/18711518 for a detailed overview) probably to an incompatibility with an old dependency. It'd be nice if the `configure` script could detect the reasons for the failure and fail with a verbose error message. Otherwise, if these system ought to be supported, the build should be fixed.

experienced with v0.9.2-826-gf093e76d

**Comment by akhuettel** [comment]
Saw the same on Gentoo and "fixed" it by updating libav from 11.* to 12.*
Not sure what the corresponding ffmpeg versions are.
